### ISSUE TITLE
baresip-android can't be build

### ISSUE THREAD

**Issue by oliexe** [juha-h/libwebrtc#4]
Baresip-android can't be built now, the new webRTC gets stuck at.

/jni/src/webrtc/rtc_base/checks.h:57.10: fatal error: "absl/meta/type_traits.h" file not found

I cant even seem to find **absl/meta/type_traits.h** in the repository (mobile branch)

using the makefile and guide on baresip-android

**Comment by juha-h** [comment]
Which guide and which baresip-android?

**Comment by juha-h** [comment]
Should work now.  See https://github.com/juha-h/libbaresip-android/issues/20.
